/*
*
*       Requirements: - form must have ID "captcha-form"
*                     - form button must have ID "captcha-button"
*
*/

var captchaSolved = false,
    styledCaptchaOverlayHTML = '<div class="valign card blue-grey darken-2 hoverable" style="display: none; width: 30%; margin: 0 auto;">' +
        '<div class="card-image" style="display: flex; justify-content: space-around; padding: 20px 3%;">' +
              '<img id="first" style="width: 40%; border: 8px solid rgba(0, 0, 0, 0.1);" src="">' +
              '<img id="second" style="width: 40%; border: 8px solid rgba(0, 0, 0, 0.1);" src="">' +
              '<span class="card-title"></span>' +
            '</div>' +
            '<div class="card-content row" style="padding: 0 15px">' +
                '<div class="input-field col s12">' +
            '<i class="material-icons prefix">keyboard</i>' +
            '<input id="icon_prefix" type="text" class="validate input">' +
            '<label for="icon_prefix">Solution</label>' +
          '</div>' +
            '</div>' +
            '<div class="card-action right-align">' +
              '<a id="submit" href="">Submit</a>' +
              '<a id="reload" href=""><i class="material-icons" style="font-size: 1.2rem">refresh</i></a>' +
            '</div>' +
    '</div>';

// append captcha DOM Node to body
// cross browser trick (https://stackoverflow.com/questions/494143/creating-a-new-dom-element-from-an-html-string-using-built-in-dom-methods-or-pro)
var div = document.createElement('div');
div.innerHTML = styledCaptchaOverlayHTML;
var captchaOverlay = div.firstChild;
// Append overlay to body with rendered captcha (display: none)
document.body.appendChild(captchaOverlay);


// Lookup form and form button element
var form = (!document.querySelectorAll('#captcha-form'))? false : document.querySelectorAll('#captcha-form')[0],
    button = (!document.querySelectorAll('#captcha-button'))? false : document.querySelectorAll('#captcha-button')[0];
if (!button) {
    throw new Error('form button element with id "captcha-button" does not exist');
}
if (!form) {
    throw new Error('form element with id "captcha-form" does not exist');
}

// 3. Add eventlistener on form button to summon overlay
var showCaptchaOverlay = function () {
    var body = document.querySelectorAll('body');

}
button.addEventListener('click', function(e) {
    if(!captchaSolved) {
        e.preventDefault();
        // show captcha overlay
    }
})


// 4. POST Form on validation and secrect key generated by Web Service
